# fly.toml file generated for pdns-admin on 2023-01-03T18:17:57+01:00

app = "pdns-admin"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PDNS_AUTH_IP = "fdaa:1:160b:0:1::3"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[statics]]
  guest_path = "/app/powerdnsadmin/static"
  url_prefix = "/static"

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 40
    soft_limit = 30
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = 10000
    grace_period = "20s"
    method = "get"
    path = "/login"
    protocol = "http"
    restart_limit = 5
    timeout = 2000
    tls_skip_verify = false